<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="68" started-at="2019-03-06T19:02:44Z" finished-at="2019-03-06T19:02:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="68" started-at="2019-03-06T19:02:44Z" finished-at="2019-03-06T19:02:44Z">
      <class name="tests.PerformanceListenerTest">
        <test-method status="PASS" signature="checkForAnomaliesTest_invalid()[pri:0, instance:tests.PerformanceListenerTest@100fc185]" name="checkForAnomaliesTest_invalid" duration-ms="51" started-at="2019-03-06T19:02:44Z" finished-at="2019-03-06T19:02:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[TestKlasse#TestMethods hat 1100 ms in Anspruche genommen; Durchschnitt ist 1000.0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: TestKlasse#TestMethods hat 1100 ms in Anspruche genommen; Durchschnitt ist 1000.0
at org.testng.Assert.fail(Assert.java:96)
at listeners.PerformanceListener.checkForAnomalies(PerformanceListener.java:71)
at tests.PerformanceListenerTest.checkForAnomaliesTest_invalid(PerformanceListenerTest.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkForAnomaliesTest_invalid -->
      </class> <!-- tests.PerformanceListenerTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
